//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayQuick
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long ID { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string identity_no { get; set; }
        public string pay_id { get; set; }
        public string occupation { get; set; }
        public Nullable<System.DateTime> appointed_date { get; set; }
        public string tax_id { get; set; }
        public string status { get; set; }
        public Nullable<decimal> basic_salary_tmp { get; set; }
        public Nullable<decimal> other_earnings1_value_tmp { get; set; }
        public string other_earnings1_descr_tmp { get; set; }
        public Nullable<decimal> paye_tmp { get; set; }
        public Nullable<decimal> uif_tmp { get; set; }
        public Nullable<decimal> providend_tmp { get; set; }
        public Nullable<decimal> other_deduction1_value_tmp { get; set; }
        public string other_deduction1_descr_tmp { get; set; }
        public Nullable<decimal> gross_pay_tmp { get; set; }
        public Nullable<decimal> total_deduction_tmp { get; set; }
        public Nullable<decimal> net_pay_tmp { get; set; }
        public Nullable<System.DateTime> pay_date_tmp { get; set; }
        public Nullable<decimal> basic_salary_jan { get; set; }
        public Nullable<decimal> other_earnings1_value_jan { get; set; }
        public string other_earnings1_descr_jan { get; set; }
        public Nullable<decimal> paye_jan { get; set; }
        public Nullable<decimal> uif_jan { get; set; }
        public Nullable<decimal> providend_jan { get; set; }
        public Nullable<decimal> other_deduction1_value_jan { get; set; }
        public string other_deduction1_descr_jan { get; set; }
        public Nullable<decimal> gross_pay_jan { get; set; }
        public Nullable<decimal> total_deduction_jan { get; set; }
        public Nullable<decimal> net_pay_jan { get; set; }
        public Nullable<System.DateTime> pay_date_jan { get; set; }
        public Nullable<decimal> basic_salary_feb { get; set; }
        public Nullable<decimal> other_earnings1_value_feb { get; set; }
        public string other_earnings1_descr_feb { get; set; }
        public Nullable<decimal> paye_feb { get; set; }
        public Nullable<decimal> uif_feb { get; set; }
        public Nullable<decimal> providend_feb { get; set; }
        public Nullable<decimal> other_deduction1_value_feb { get; set; }
        public string other_deduction1_descr_feb { get; set; }
        public Nullable<decimal> gross_pay_feb { get; set; }
        public Nullable<decimal> total_deduction_feb { get; set; }
        public Nullable<decimal> net_pay_feb { get; set; }
        public Nullable<System.DateTime> pay_date_feb { get; set; }
        public Nullable<decimal> basic_salary_mar { get; set; }
        public Nullable<decimal> other_earnings1_value_mar { get; set; }
        public string other_earnings1_descr_mar { get; set; }
        public Nullable<decimal> paye_mar { get; set; }
        public Nullable<decimal> uif_mar { get; set; }
        public Nullable<decimal> providend_mar { get; set; }
        public Nullable<decimal> other_deduction1_value_mar { get; set; }
        public string other_deduction1_descr_mar { get; set; }
        public Nullable<decimal> gross_pay_mar { get; set; }
        public Nullable<decimal> total_deduction_mar { get; set; }
        public Nullable<decimal> net_pay_mar { get; set; }
        public Nullable<System.DateTime> pay_date_mar { get; set; }
        public Nullable<decimal> basic_salary_apr { get; set; }
        public Nullable<decimal> other_earnings1_value_apr { get; set; }
        public string other_earnings1_descr_apr { get; set; }
        public Nullable<decimal> paye_apr { get; set; }
        public Nullable<decimal> uif_apr { get; set; }
        public Nullable<decimal> providend_apr { get; set; }
        public Nullable<decimal> other_deduction1_value_apr { get; set; }
        public string other_deduction1_descr_apr { get; set; }
        public Nullable<decimal> gross_pay_apr { get; set; }
        public Nullable<decimal> total_deduction_apr { get; set; }
        public Nullable<decimal> net_pay_apr { get; set; }
        public Nullable<System.DateTime> pay_date_apr { get; set; }
        public Nullable<decimal> basic_salary_may { get; set; }
        public Nullable<decimal> other_earnings1_value_may { get; set; }
        public string other_earnings1_descr_may { get; set; }
        public Nullable<decimal> paye_may { get; set; }
        public Nullable<decimal> uif_may { get; set; }
        public Nullable<decimal> providend_may { get; set; }
        public Nullable<decimal> other_deduction1_value_may { get; set; }
        public string other_deduction1_descr_may { get; set; }
        public Nullable<decimal> gross_pay_may { get; set; }
        public Nullable<decimal> total_deduction_may { get; set; }
        public Nullable<decimal> net_pay_may { get; set; }
        public Nullable<System.DateTime> pay_date_may { get; set; }
        public Nullable<decimal> basic_salary_jun { get; set; }
        public Nullable<decimal> other_earnings1_value_jun { get; set; }
        public string other_earnings1_descr_jun { get; set; }
        public Nullable<decimal> paye_jun { get; set; }
        public Nullable<decimal> uif_jun { get; set; }
        public Nullable<decimal> providend_jun { get; set; }
        public Nullable<decimal> other_deduction1_value_jun { get; set; }
        public string other_deduction1_descr_jun { get; set; }
        public Nullable<decimal> gross_pay_jun { get; set; }
        public Nullable<decimal> total_deduction_jun { get; set; }
        public Nullable<decimal> net_pay_jun { get; set; }
        public Nullable<System.DateTime> pay_date_jun { get; set; }
        public Nullable<decimal> basic_salary_jul { get; set; }
        public Nullable<decimal> other_earnings1_value_jul { get; set; }
        public string other_earnings1_descr_jul { get; set; }
        public Nullable<decimal> paye_jul { get; set; }
        public Nullable<decimal> uif_jul { get; set; }
        public Nullable<decimal> providend_jul { get; set; }
        public Nullable<decimal> other_deduction1_value_jul { get; set; }
        public string other_deduction1_descr_jul { get; set; }
        public Nullable<decimal> gross_pay_jul { get; set; }
        public Nullable<decimal> total_deduction_jul { get; set; }
        public Nullable<decimal> net_pay_jul { get; set; }
        public Nullable<System.DateTime> pay_date_jul { get; set; }
        public Nullable<decimal> basic_salary_aug { get; set; }
        public Nullable<decimal> other_earnings1_value_aug { get; set; }
        public string other_earnings1_descr_aug { get; set; }
        public Nullable<decimal> paye_aug { get; set; }
        public Nullable<decimal> uif_aug { get; set; }
        public Nullable<decimal> providend_aug { get; set; }
        public Nullable<decimal> other_deduction1_value_aug { get; set; }
        public string other_deduction1_descr_aug { get; set; }
        public Nullable<decimal> gross_pay_aug { get; set; }
        public Nullable<decimal> total_deduction_aug { get; set; }
        public Nullable<decimal> net_pay_aug { get; set; }
        public Nullable<System.DateTime> pay_date_aug { get; set; }
        public Nullable<decimal> basic_salary_sep { get; set; }
        public Nullable<decimal> other_earnings1_value_sep { get; set; }
        public string other_earnings1_descr_sep { get; set; }
        public Nullable<decimal> paye_sep { get; set; }
        public Nullable<decimal> uif_sep { get; set; }
        public Nullable<decimal> providend_sep { get; set; }
        public Nullable<decimal> other_deduction1_value_sep { get; set; }
        public string other_deduction1_descr_sep { get; set; }
        public Nullable<decimal> gross_pay_sep { get; set; }
        public Nullable<decimal> total_deduction_sep { get; set; }
        public Nullable<decimal> net_pay_sep { get; set; }
        public Nullable<System.DateTime> pay_date_sep { get; set; }
        public Nullable<decimal> basic_salary_oct { get; set; }
        public Nullable<decimal> other_earnings1_value_oct { get; set; }
        public string other_earnings1_descr_oct { get; set; }
        public Nullable<decimal> paye_oct { get; set; }
        public Nullable<decimal> uif_oct { get; set; }
        public Nullable<decimal> providend_oct { get; set; }
        public Nullable<decimal> other_deduction1_value_oct { get; set; }
        public string other_deduction1_descr_oct { get; set; }
        public Nullable<decimal> gross_pay_oct { get; set; }
        public Nullable<decimal> total_deduction_oct { get; set; }
        public Nullable<decimal> net_pay_oct { get; set; }
        public Nullable<System.DateTime> pay_date_oct { get; set; }
        public Nullable<decimal> basic_salary_nov { get; set; }
        public Nullable<decimal> other_earnings1_value_nov { get; set; }
        public string other_earnings1_descr_nov { get; set; }
        public Nullable<decimal> paye_nov { get; set; }
        public Nullable<decimal> uif_nov { get; set; }
        public Nullable<decimal> providend_nov { get; set; }
        public Nullable<decimal> other_deduction1_value_nov { get; set; }
        public string other_deduction1_descr_nov { get; set; }
        public Nullable<decimal> gross_pay_nov { get; set; }
        public Nullable<decimal> total_deduction_nov { get; set; }
        public Nullable<decimal> net_pay_nov { get; set; }
        public Nullable<System.DateTime> pay_date_nov { get; set; }
        public Nullable<decimal> basic_salary_dec { get; set; }
        public Nullable<decimal> other_earnings1_value_dec { get; set; }
        public string other_earnings1_descr_dec { get; set; }
        public Nullable<decimal> paye_dec { get; set; }
        public Nullable<decimal> uif_dec { get; set; }
        public Nullable<decimal> providend_dec { get; set; }
        public Nullable<decimal> other_deduction1_value_dec { get; set; }
        public string other_deduction1_descr_dec { get; set; }
        public Nullable<decimal> gross_pay_dec { get; set; }
        public Nullable<decimal> total_deduction_dec { get; set; }
        public Nullable<decimal> net_pay_dec { get; set; }
        public Nullable<System.DateTime> pay_date_dec { get; set; }
        public Nullable<decimal> basic_salary_xtr { get; set; }
        public Nullable<decimal> other_earnings1_value_xtr { get; set; }
        public string other_earnings1_descr_xtr { get; set; }
        public Nullable<decimal> paye_xtr { get; set; }
        public Nullable<decimal> uif_xtr { get; set; }
        public Nullable<decimal> providend_xtr { get; set; }
        public Nullable<decimal> other_deduction1_value_xtr { get; set; }
        public string other_deduction1_descr_xtr { get; set; }
        public Nullable<decimal> gross_pay_xtr { get; set; }
        public Nullable<decimal> total_deduction_xtr { get; set; }
        public Nullable<decimal> net_pay_xtr { get; set; }
        public Nullable<System.DateTime> pay_date_xtr { get; set; }

        //Method
        public void blankEmp(Employee retEmp)
        {
            ID = 0;
            lastname = "";
            firstname = "";
            identity_no = "";
            pay_id = "";
            occupation = "";
            appointed_date = DateTime.Today;
            tax_id = "";
            status = "Active";
        }
    }
}
