//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayQuick
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public long ID { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string identity_no { get; set; }
        public string pay_id { get; set; }
        public string occupation { get; set; }
        public Nullable<System.DateTime> appointed_date { get; set; }
        public string tax_id { get; set; }
        public string status { get; set; }
        public Nullable<decimal> basic_salary { get; set; }
        public Nullable<decimal> other_earnings1_value { get; set; }
        public string other_earnings1_descr { get; set; }
        public Nullable<decimal> paye { get; set; }
        public Nullable<decimal> uif { get; set; }
        public Nullable<decimal> providend { get; set; }
        public Nullable<decimal> other_deduction1_value { get; set; }
        public string other_deduction1_descr { get; set; }
        public Nullable<decimal> gross_pay { get; set; }
        public Nullable<decimal> total_deduction { get; set; }
        public Nullable<decimal> net_pay { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
    }
}
